global using System.Linq;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Net.Http;
global using System.Threading.Tasks;
global using System.Threading;
global using Ocelli.OpenShopify.Tests.Fixtures;
global using Ocelli.OpenShopify.Tests.Helpers;
global using Xunit;
global using Xunit.Abstractions;
global using Xunit.Sdk;
global using SkipException = Xunit.Sdk.SkipException;