//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace OpenShopify.Admin.Builder
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class ShopControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>
        /// Retrieves the shop's configuration
        /// </summary>
        /// <param name="fields">A comma-separated list of fields to include in the response.</param>
        /// <returns>Retrieves the shop's configuration</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/shop.json")]
        public abstract System.Threading.Tasks.Task RetrieveTheShopsConfiguration([Microsoft.AspNetCore.Mvc.FromQuery] string? fields = null);

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Shop
    {
        /// <summary>
        /// The shop's street address.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("address1")]
        public string? Address1 { get; set; } = default!;

        /// <summary>
        /// The optional second line of the shop's street address.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("address2")]
        public string? Address2 { get; set; } = default!;

        /// <summary>
        /// Whether the shop is capable of accepting payments directly through the Checkout API.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("checkout_api_supported")]
        public string? Checkout_api_supported { get; set; } = default!;

        /// <summary>
        /// The shop's city.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("city")]
        public string? City { get; set; } = default!;

        /// <summary>
        /// The shop's country. In most cases, this value matches the country_code.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string? Country { get; set; } = default!;

        /// <summary>
        /// The two-letter country code corresponding to the shop's country.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("country_code")]
        public string? Country_code { get; set; } = default!;

        /// <summary>
        /// The shop's normalized country name.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("country_name")]
        public string? Country_name { get; set; } = default!;

        /// <summary>
        /// Whether the shop is applying taxes on a per-county basis. Only applicable to shops based in the US. Valid values: true or null."
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("county_taxes")]
        public string? County_taxes { get; set; } = default!;

        /// <summary>
        /// The date and time (ISO 8601) when the shop was created.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public string? Created_at { get; set; } = default!;

        /// <summary>
        /// The contact email used for communication between the shop owner and the customer.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("customer_email")]
        public string? Customer_email { get; set; } = default!;

        /// <summary>
        /// The three-letter code (ISO 4217 format) for the shop's default currency.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("currency")]
        public string? Currency { get; set; } = default!;

        /// <summary>
        /// The shop's domain.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("domain")]
        public string? Domain { get; set; } = default!;

        /// <summary>
        /// A list of enabled currencies (ISO 4217 format) that the shop accepts. Merchants can enable currencies from their Shopify Payments settings in the Shopify Admin.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("enabled_presentment_currencies")]
        public string? Enabled_presentment_currencies { get; set; } = default!;

        /// <summary>
        /// Whether the shop is eligible to receive a free credit card reader from Shopify.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("eligible_for_card_reader_giveaway")]
        public string? Eligible_for_card_reader_giveaway { get; set; } = default!;

        /// <summary>
        /// Whether the shop is eligible to use Shopify Payments.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("eligible_for_payments")]
        public string? Eligible_for_payments { get; set; } = default!;

        /// <summary>
        /// The contact email used for communication between Shopify and the shop owner.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string? Email { get; set; } = default!;

        /// <summary>
        /// This field has been deprecated, and is currently unused. Hardcoded to true.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("finances")]
        public string? Finances { get; set; } = default!;

        /// <summary>
        /// As of API version 2021-07, this field has been deprecated and is currently unused. Previously indicated whether the shop forced requests made to its resources to be made over SSL using the HTTPS protocol. All requests now use HTTPS, so force_ssl is always true.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("force_ssl")]
        public string? Force_ssl { get; set; } = default!;

        /// <summary>
        /// The GSuite URL for the store, if applicable.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("google_apps_domain")]
        public string? Google_apps_domain { get; set; } = default!;

        /// <summary>
        /// Whether the GSuite login is enabled. Shops with this feature will be able to log in through the GSuite login page. Valid values: true, null
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("google_apps_login_enabled")]
        public string? Google_apps_login_enabled { get; set; } = default!;

        /// <summary>
        /// Whether any active discounts exist for the shop.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("has_discounts")]
        public string? Has_discounts { get; set; } = default!;

        /// <summary>
        /// Whether any active gift cards exist for the shop.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("has_gift_cards")]
        public string? Has_gift_cards { get; set; } = default!;

        /// <summary>
        /// Whether the shop has an online store.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("has_storefront")]
        public string? Has_storefront { get; set; } = default!;

        /// <summary>
        /// The name of the timezone assigned by the IANA.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("iana_timezone")]
        public string? Iana_timezone { get; set; } = default!;

        /// <summary>
        /// The ID for the shop. A 64-bit unsigned integer.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        /// <summary>
        /// The latitude of the shop's location.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("latitude")]
        public string? Latitude { get; set; } = default!;

        /// <summary>
        /// The longitude of the shop's location.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("longitude")]
        public string? Longitude { get; set; } = default!;

        /// <summary>
        /// A string representing the way currency is formatted when the currency isn't specified.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("money_format")]
        public string? Money_format { get; set; } = default!;

        /// <summary>
        /// A string representing the way currency is formatted in email notifications when the currency isn't specified.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("money_in_emails_format")]
        public string? Money_in_emails_format { get; set; } = default!;

        /// <summary>
        /// A string representing the way currency is formatted when the currency is specified.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("money_with_currency_format")]
        public string? Money_with_currency_format { get; set; } = default!;

        /// <summary>
        /// A string representing the way currency is formatted in email notifications when the currency is specified.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("money_with_currency_in_emails_format")]
        public string? Money_with_currency_in_emails_format { get; set; } = default!;

        /// <summary>
        /// Whether the shop has enabled multiple locations.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("multi_location_enabled")]
        public string? Multi_location_enabled { get; set; } = default!;

        /// <summary>
        /// The shop's .myshopify.com domain.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("myshopify_domain")]
        public string? Myshopify_domain { get; set; } = default!;

        /// <summary>
        /// The name of the shop.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        /// <summary>
        /// Whether the password protection page is enabled on the shop's online store.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("password_enabled")]
        public string? Password_enabled { get; set; } = default!;

        /// <summary>
        /// The contact phone number for the shop.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("phone")]
        public string? Phone { get; set; } = default!;

        /// <summary>
        /// The display name of the Shopify plan the shop is on.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("plan_display_name")]
        public string? Plan_display_name { get; set; } = default!;

        /// <summary>
        /// Whether the pre-launch page is enabled on the shop's online store.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pre_launch_enabled")]
        public string? Pre_launch_enabled { get; set; } = default!;

        /// <summary>
        /// The cookie consent level defined on the shop's online store.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("cookie_consent_level")]
        public string? Cookie_consent_level { get; set; } = default!;

        /// <summary>
        /// The name of the Shopify plan the shop is on.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("plan_name")]
        public string? Plan_name { get; set; } = default!;

        /// <summary>
        /// The shop's primary locale, as configured in the language settings of the shop's theme.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("primary_locale")]
        public string? Primary_locale { get; set; } = default!;

        /// <summary>
        /// Formerly used for the ID of the shipping origin location (read only).
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("primary_location_id")]
        public string? Primary_location_id { get; set; } = default!;

        /// <summary>
        /// The shop's normalized province or state name.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("province")]
        public string? Province { get; set; } = default!;

        /// <summary>
        /// The two- or three-letter code for the shop's province or state.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("province_code")]
        public string? Province_code { get; set; } = default!;

        /// <summary>
        /// Whether the shop requires an extra Shopify Payments agreement.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("requires_extra_payments_agreement")]
        public string? Requires_extra_payments_agreement { get; set; } = default!;

        /// <summary>
        /// Whether the shop has any outstanding setup steps.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("setup_required")]
        public string? Setup_required { get; set; } = default!;

        /// <summary>
        /// The username of the shop owner.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("shop_owner")]
        public string? Shop_owner { get; set; } = default!;

        /// <summary>
        /// The handle of the partner account that referred the merchant to Shopify, if applicable.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("source")]
        public string? Source { get; set; } = default!;

        /// <summary>
        /// Whether applicable taxes are included in product prices. Valid values: true or null.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("taxes_included")]
        public string? Taxes_included { get; set; } = default!;

        /// <summary>
        /// Whether taxes are charged for shipping. Valid values: true or false.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("tax_shipping")]
        public string? Tax_shipping { get; set; } = default!;

        /// <summary>
        /// The name of the timezone the shop is in.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("timezone")]
        public string? Timezone { get; set; } = default!;

        /// <summary>
        /// Whether transactional SMS sent by Shopify are disabled on the shop's online store.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("transactional_sms_disabled")]
        public string? Transactional_sms_disabled { get; set; } = default!;

        /// <summary>
        /// The date and time (ISO 8601) when the shop was last updated.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public string? Updated_at { get; set; } = default!;

        /// <summary>
        /// The default unit of weight measurement for the shop.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("weight_unit")]
        public string? Weight_unit { get; set; } = default!;

        /// <summary>
        /// The shop's zip or postal code.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("zip")]
        public string? Zip { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603