//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace OpenShopify.Admin.Builder
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class ResourceFeedbackControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>
        /// Create a new ResourceFeedback
        /// </summary>
        /// <param name="feedback_generated_at">An ISO 8601 date and time indicating when the feedback was generated by your app.</param>
        /// <param name="messages">An array containing a single message.
        /// <br/>See &lt;a href="#formatting-the-resource-feedback-field-{{ current_version }}"&gt;
        /// <br/>&lt;em&gt;Formatting the resource feedback message field&lt;/em&gt;&lt;/a&gt; for formatting requirements.</param>
        /// <param name="state">Must be one of the following values:</param>
        /// <returns>Create a new ResourceFeedback</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/resource_feedback.json")]
        public abstract System.Threading.Tasks.Task CreateNewResourcefeedback([Microsoft.AspNetCore.Mvc.FromQuery] string feedback_generated_at, [Microsoft.AspNetCore.Mvc.FromQuery] string messages, [Microsoft.AspNetCore.Mvc.FromQuery] string state);

        /// <summary>
        /// Receive a list of all ResourceFeedbacks
        /// </summary>
        /// <returns>Receive a list of all ResourceFeedbacks</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/resource_feedback.json")]
        public abstract System.Threading.Tasks.Task ReceiveListOfAllResourcefeedbacks();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ResourceFeedback
    {
        /// <summary>
        /// DateTime when the resource feedback record was stored by Shopify.
        /// <br/> Type: ISO 8601 UTC DateTime as string with year, month (or week), day, hour, minute, second, time zone.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public string? Created_at { get; set; } = default!;

        /// <summary>
        /// DateTime when the resource feedback record was last updated by Shopify.
        /// <br/> Type: ISO 8601 UTC DateTime as string with year, month (or week), day, hour, minute, second, time zone.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public string? Updated_at { get; set; } = default!;

        /// <summary>
        /// Unique id of the resource.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("resource_id")]
        public string? Resource_id { get; set; } = default!;

        /// <summary>
        /// Type of resource for which feedback is returned. eg. Shop, Product.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("resource_type")]
        public string? Resource_type { get; set; } = default!;

        /// <summary>
        /// Indicates the state that the Shop or resource is in, from the perspective of your app. Valid values are requires_action, or success.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        public string? State { get; set; } = default!;

        /// <summary>
        /// A concise set of copy strings to be displayed to merchants, to guide them in resolving problems your app
        /// <br/> encounters when trying to make use of their Shop and its resources.
        /// <br/> 
        /// <br/>
        /// <br/> 
        /// <br/> Required only when state is requires_action. Disallowed when state is success.
        /// <br/> 
        /// <br/>
        /// <br/> 
        /// <br/> Content restrictions for Shop feedback:
        /// <br/> one message up to 100 characters long.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("messages")]
        public string? Messages { get; set; } = default!;

        /// <summary>
        /// The time at which the payload is constructed. Used to help determine whether incoming feedback is
        /// <br/> outdated compared to feedback already received, and if it should be ignored upon arrival.
        /// <br/> Type: ISO 8601 UTC datetime as string
        /// <br/> with year, month [or week], day, hour, minute, second, millisecond, and time zone.
        /// <br/> 
        /// <br/>
        /// <br/> 
        /// <br/> Note
        /// <br/> If you queue a Feedback API payload for delivery at a later time, do not update this value
        /// <br/> when the API call is actually made; ensure that the current time is set when building the payload.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("feedback_generated_at")]
        public string? Feedback_generated_at { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603