openapi: 3.0.1
info:
  title: Metafield
  description: Metafield
  version: '2022-07'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-07'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /metafields.json:
    get:
      tags:
        - Metafield
      summary: Retrieve a list of metafields from the resource's endpoint
      operationId: ListMetafieldsFromResourcesEndpoint
      parameters:
        - name: created_at_max
          in: query
          description: 'Show metafields created before date (format: 2022-02-25T16:15:47-04:00)'
          schema:
            type: string
            format: date-time
        - name: created_at_min
          in: query
          description: 'Show metafields created after date (format: 2022-02-25T16:15:47-04:00)'
          schema:
            type: string
            format: date-time
        - name: fields
          in: query
          description: 'Retrieve only certain fields, specified by a comma-separated list of fields names.'
          schema:
            type: string
        - name: key
          in: query
          description: Show metafields with given key
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of results to show on a page.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
        - name: namespace
          in: query
          schema:
            type: string
        - name: since_id
          in: query
          description: Show metafields created after the specified ID.
          schema:
            type: integer
            format: int64
        - name: type
          in: query
          description: 'The type of data that the metafield stores in the `value` field.Refer to the list of [supported types](/apps/metafields/types).'
          schema:
            type: string
        - name: updated_at_max
          in: query
          description: 'Show metafields last updated before date (format: 2022-02-25T16:15:47-04:00)'
          schema:
            type: string
            format: date-time
        - name: updated_at_min
          in: query
          description: 'Show metafields last updated after date (format: 2022-02-25T16:15:47-04:00)'
          schema:
            type: string
            format: date-time
        - name: value_type
          in: query
          description: The legacy type information for the stored value. Replaced by `type`
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            Link:
              description: 'The link header includes a `rel` parameter, where `relation-types` describes the relation of the linked page to the current page of results. The value can either be `previous` or `next`. If your initial request doesn''t return enough records to generate an additional page of results, then the response won''t have a link header.'
              schema:
                type: string
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetafieldList'
    post:
      tags:
        - Metafield
      summary: Create a metafield
      operationId: CreateMetafield
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMetafieldRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateMetafieldRequest'
        required: true
      responses:
        '201':
          description: Created
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetafieldItem'
        '400':
          description: Bad Request
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetafieldError'
  /metafields/count.json:
    get:
      tags:
        - Metafield
      summary: Retrieve a count of a resource's metafields.
      operationId: CountResourcesMetafields
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountItem'
  '/metafields/{metafield_id}.json':
    get:
      tags:
        - Metafield
      summary: Retrieve a specific metafield
      operationId: GetMetafield
      parameters:
        - name: metafield_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: fields
          in: query
          description: 'Retrieve only certain fields, specified by a comma-separated list of fields names.'
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetafieldItem'
    put:
      tags:
        - Metafield
      summary: Updates a metafield
      operationId: UpdateMetafield
      parameters:
        - name: metafield_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMetafieldRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateMetafieldRequest'
        required: true
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetafieldItem'
    delete:
      tags:
        - Metafield
      summary: Deletes a metafield by its ID
      operationId: DeleteMetafield
      parameters:
        - name: metafield_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
components:
  schemas:
    CountItem:
      type: object
      properties:
        count:
          type: integer
          format: int32
      additionalProperties: { }
    CreateMetafield:
      type: object
      properties:
        description:
          type: string
          description: A description of the information that the metafield contains.
          nullable: true
        key:
          type: string
          description: 'The key of the metafield. Keys can be up to 30 characters long and can contain alphanumeric characters, hyphens, underscores, and periods.'
          nullable: true
        namespace:
          type: string
          description: A container for a group of metafields. Grouping metafields within a namespace prevents your metafields from conflicting with other metafields with the same key name. Must have between 3-20 characters.
          nullable: true
        owner_id:
          type: integer
          description: The unique ID of the resource that the metafield is attached to.
          format: int64
          nullable: true
        owner_resource:
          type: string
          description: The type of resource that the metafield is attached to.
          nullable: true
        value:
          description: 'The data to store in the metafield. The value is always stored as a string, regardless of the metafield''s type.'
          nullable: true
        type:
          $ref: '#/components/schemas/MetafieldType'
        value_type:
          type: string
          description: "<aside class=\"note caution\"> \r\n\r\n#### Caution\r\n\r\n`value_type` is deprecated and replaced by `type` in API version 2021-07.\r\n </aside> The legacy type information for the stored value. Valid values: `string`, `integer`, `json_string`."
          nullable: true
          deprecated: true
      additionalProperties: false
    CreateMetafieldRequest:
      required:
        - metafield
      type: object
      properties:
        metafield:
          $ref: '#/components/schemas/CreateMetafield'
      additionalProperties: false
    Metafield:
      required:
        - id
      type: object
      properties:
        description:
          type: string
          description: A description of the information that the metafield contains.
          nullable: true
        key:
          type: string
          description: 'The key of the metafield. Keys can be up to 30 characters long and can contain alphanumeric characters, hyphens, underscores, and periods.'
          nullable: true
        namespace:
          type: string
          description: A container for a group of metafields. Grouping metafields within a namespace prevents your metafields from conflicting with other metafields with the same key name. Must have between 3-20 characters.
          nullable: true
        owner_id:
          type: integer
          description: The unique ID of the resource that the metafield is attached to.
          format: int64
          nullable: true
        owner_resource:
          type: string
          description: The type of resource that the metafield is attached to.
          nullable: true
        value:
          description: 'The data to store in the metafield. The value is always stored as a string, regardless of the metafield''s type.'
          nullable: true
        type:
          $ref: '#/components/schemas/MetafieldType'
        value_type:
          type: string
          description: "<aside class=\"note caution\"> \r\n\r\n#### Caution\r\n\r\n`value_type` is deprecated and replaced by `type` in API version 2021-07.\r\n </aside> The legacy type information for the stored value. Valid values: `string`, `integer`, `json_string`."
          nullable: true
          deprecated: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
        created_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the asset was created.'
          format: date-time
          nullable: true
        updated_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when an asset was last updated.'
          format: date-time
          nullable: true
      additionalProperties: { }
    MetafieldError:
      required:
        - errors
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/MetafieldErrorDetails'
      additionalProperties: { }
    MetafieldErrorDetails:
      type: object
      properties:
        type:
          type: array
          items:
            type: string
          nullable: true
        namespace:
          type: array
          items:
            type: string
          nullable: true
        key:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: { }
    MetafieldItem:
      required:
        - metafield
      type: object
      properties:
        metafield:
          $ref: '#/components/schemas/Metafield'
      additionalProperties: { }
    MetafieldList:
      required:
        - metafields
      type: object
      properties:
        metafields:
          type: array
          items:
            $ref: '#/components/schemas/Metafield'
      additionalProperties: { }
    MetafieldType:
      enum:
        - boolean
        - color
        - date
        - date_time
        - dimension
        - file_reference
        - json
        - multi_line_text_field
        - number_decimal
        - number_integer
        - page_reference
        - product_reference
        - rating
        - single_line_text_field
        - variant_reference
        - volume
        - weight
      type: string
      additionalProperties: { }
    UpdateMetafield:
      required:
        - id
      type: object
      properties:
        description:
          type: string
          description: A description of the information that the metafield contains.
          nullable: true
        key:
          type: string
          description: 'The key of the metafield. Keys can be up to 30 characters long and can contain alphanumeric characters, hyphens, underscores, and periods.'
          nullable: true
        namespace:
          type: string
          description: A container for a group of metafields. Grouping metafields within a namespace prevents your metafields from conflicting with other metafields with the same key name. Must have between 3-20 characters.
          nullable: true
        owner_id:
          type: integer
          description: The unique ID of the resource that the metafield is attached to.
          format: int64
          nullable: true
        owner_resource:
          type: string
          description: The type of resource that the metafield is attached to.
          nullable: true
        value:
          description: 'The data to store in the metafield. The value is always stored as a string, regardless of the metafield''s type.'
          nullable: true
        type:
          $ref: '#/components/schemas/MetafieldType'
        value_type:
          type: string
          description: "<aside class=\"note caution\"> \r\n\r\n#### Caution\r\n\r\n`value_type` is deprecated and replaced by `type` in API version 2021-07.\r\n </aside> The legacy type information for the stored value. Valid values: `string`, `integer`, `json_string`."
          nullable: true
          deprecated: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: false
    UpdateMetafieldRequest:
      required:
        - metafield
      type: object
      properties:
        metafield:
          $ref: '#/components/schemas/UpdateMetafield'
      additionalProperties: false
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]