openapi: 3.0.1
info:
  title: Access
  description: Authentication and Authorization
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: sample_store
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
paths:
  /storefront_access_tokens.json:
    post:
      tags:
        - StorefrontAccessToken
      summary: Creates a new StorefrontAccessToken
      operationId: CreateNewStorefrontAccessToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStorefrontAccessTokenRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateStorefrontAccessTokenRequest'
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorefrontAccessTokenItem'
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - StorefrontAccessToken
      summary: Retrieves a list of storefront access tokens that have been issued
      operationId: RetrieveListOfStorefrontAccessTokensThatHaveBeenIssued
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorefrontAccessTokenList'
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/storefront_access_tokens/{storefront_access_token_id}.json':
    delete:
      tags:
        - StorefrontAccessToken
      summary: Deletes an existing storefront access token
      operationId: DeleteExistingStorefrontAccessToken
      parameters:
        - name: storefront_access_token_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CreateStorefrontAccessToken:
      type: object
      properties:
        access_token:
          type: string
          description: The issued public access token.
          nullable: true
        access_scope:
          type: string
          description: 'An application-dependant, comma separated list of permissions associated with the token.'
          nullable: true
        created_at:
          type: string
          description: The date and time when the public access token was created. The API returns this value in ISO 8601 format.
          format: date-time
          nullable: true
        title:
          type: string
          description: "An arbitrary title for each token determined by the developer/application, used for reference purposes.\r\nNo constraint on uniqueness."
          nullable: true
      additionalProperties: { }
    CreateStorefrontAccessTokenRequest:
      type: object
      properties:
        storefront_access_token:
          $ref: '#/components/schemas/CreateStorefrontAccessToken'
      additionalProperties: { }
    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
    StorefrontAccessToken:
      required:
        - id
      type: object
      properties:
        access_token:
          type: string
          description: The issued public access token.
          nullable: true
        access_scope:
          type: string
          description: 'An application-dependant, comma separated list of permissions associated with the token.'
          nullable: true
        created_at:
          type: string
          description: The date and time when the public access token was created. The API returns this value in ISO 8601 format.
          format: date-time
          nullable: true
        title:
          type: string
          description: "An arbitrary title for each token determined by the developer/application, used for reference purposes.\r\nNo constraint on uniqueness."
          nullable: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: { }
    StorefrontAccessTokenItem:
      type: object
      properties:
        storefront_access_token:
          $ref: '#/components/schemas/StorefrontAccessToken'
      additionalProperties: { }
    StorefrontAccessTokenList:
      type: object
      properties:
        storefront_access_tokens:
          type: array
          items:
            $ref: '#/components/schemas/StorefrontAccessToken'
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]