openapi: 3.0.1
info:
  title: Plus
  description: Plus
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: sample_store
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
paths:
  /gift_cards.json:
    get:
      tags:
        - GiftCard
      summary: Retrieves a list of gift cards
      operationId: RetrieveListOfGiftCards
      parameters:
        - name: fields
          in: query
          description: 'Show only certain fields, specified by a comma-separated list of field names.'
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of results to show.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          schema:
            type: string
        - name: since_id
          in: query
          description: Restrict results to after the specified ID.
          schema:
            type: integer
            format: int32
        - name: status
          in: query
          description: 'Retrieve gift cards with a given status. Valid values:'
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - GiftCard
      summary: Creates a gift card
      operationId: CreateGiftCard
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GiftCardItem'
          application/*+json:
            schema:
              $ref: '#/components/schemas/GiftCardItem'
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/gift_cards/{gift_card_id}.json':
    get:
      tags:
        - GiftCard
      summary: Retrieves a single gift card
      operationId: RetrieveSingleGiftCard
      parameters:
        - name: gift_card_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - GiftCard
      summary: Updates an existing gift card
      operationId: UpdateExistingGiftCard
      parameters:
        - name: gift_card_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GiftCardItem'
          application/*+json:
            schema:
              $ref: '#/components/schemas/GiftCardItem'
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /gift_cards/count.json:
    get:
      tags:
        - GiftCard
      summary: Retrieves a count of gift cards
      operationId: RetrieveCountOfGiftCards
      parameters:
        - name: status
          in: query
          description: 'Count gift cards with a given status. Valid values:'
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GiftCardCount'
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/gift_cards/{gift_card_id}/disable.json':
    post:
      tags:
        - GiftCard
      summary: Disables a gift card
      operationId: DisableGiftCard
      parameters:
        - name: gift_card_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /gift_cards/search.json:
    get:
      tags:
        - GiftCard
      summary: Searches for gift cards
      operationId: SearchForGiftCards
      parameters:
        - name: fields
          in: query
          description: 'Show only certain fields, specified by a comma-separated list of field names.'
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of results to retrieve.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          schema:
            type: string
        - name: order
          in: query
          description: The field and direction to order results by.
          schema:
            type: string
        - name: query
          in: query
          description: The text to search for.
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users.json:
    get:
      tags:
        - User
      summary: Retrieves a list of all users
      operationId: RetrieveListOfAllUsers
      parameters:
        - name: limit
          in: query
          description: The maximum number of results to show on a page.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/users/{user_id}.json':
    get:
      tags:
        - User
      summary: Retrieves a single user
      operationId: RetrieveSingleUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users/current.json:
    get:
      tags:
        - User
      summary: Retrieves the currently logged-in user
      operationId: RetrieveCurrentlyLoggedInUser
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
    GiftCard:
      type: object
      properties:
        id:
          type: integer
          description: The object's unique id.
          format: int64
          nullable: true
        admin_graphql_api_id:
          type: string
          nullable: true
        balance:
          type: number
          description: Returns the amount of money remaining on the gift card.
          format: double
          nullable: true
        created_at:
          type: string
          description: The date and time when the gift card was created.
          format: date-time
          nullable: true
        updated_at:
          type: string
          description: The date and time when the gift card was updated.
          format: date-time
          nullable: true
        currency:
          type: string
          description: The three letter code (ISO 4217) for the currency used for the gift card.
          nullable: true
        initial_value:
          type: number
          description: Returns the initial amount of money on the gift card.
          format: double
          nullable: true
        disabled_at:
          type: string
          description: The date and time when the gift card was disabled.
          format: date-time
          nullable: true
        expires_on:
          type: string
          description: The date and time when the gift card will expire.
          format: date-time
          nullable: true
        line_item_id:
          type: integer
          description: A unique numeric identifier of the line_item that caused the creation of this gift card (if it was created by an order).
          format: int64
          nullable: true
        api_client_id:
          type: integer
          description: A unique numeric identifier of the application that issued the gift card (if it was issued by an application).
          format: int64
          nullable: true
        user_id:
          type: integer
          description: A unique numeric identifier of the user that issued the gift card (if it was issued by a user).
          format: int64
          nullable: true
        customer_id:
          type: integer
          description: The id of a customer who is associated with this gift card.
          format: int64
          nullable: true
        note:
          type: string
          description: The text of an optional note that a shop owner can attach to the gift card. Not visible to merchants.
          nullable: true
        template_suffix:
          type: string
          description: 'When specified, the gift card will be rendered using gift_card.SUFFIX.liquid instead of gift_card.liquid.'
          nullable: true
        last_characters:
          type: string
          description: 'The last four characters of the gift card code. Because gift cards are alternate payment methods, the full code cannot be retrieved.'
          nullable: true
        order_id:
          type: integer
          description: A unique numeric identifier of the order that caused the creation of this gift card (if it was created by an order).
          format: int64
          nullable: true
        code:
          type: string
          description: Thethe gift card code. Only for Creation
          nullable: true
      additionalProperties: { }
    GiftCardCount:
      type: object
      properties:
        count:
          type: integer
          format: int32
      additionalProperties: { }
    GiftCardItem:
      type: object
      properties:
        gift_card:
          $ref: '#/components/schemas/GiftCard'
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]