openapi: 3.0.1
info:
  title: Tender Transaction
  description: Tender Transaction
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /tender_transactions.json:
    get:
      tags:
        - TenderTransaction
      summary: Retrieves a list of tender transactions
      operationId: ListTenderTransactions
      parameters:
        - name: limit
          in: query
          description: The maximum number of results to retrieve.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
        - name: order
          in: query
          description: Show tender transactions ordered by processed_at in ascending or descending order.
          schema:
            type: string
        - name: processed_at
          in: query
          description: Show tender transactions processed at the specified date.
          schema:
            type: string
            format: date-time
        - name: processed_at_max
          in: query
          description: Show tender transactions processed_at or before the specified date.
          schema:
            type: string
            format: date-time
        - name: processed_at_min
          in: query
          description: Show tender transactions processed_at or after the specified date.
          schema:
            type: string
            format: date-time
        - name: since_id
          in: query
          description: Retrieve only transactions after the specified ID.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]