openapi: 3.0.1
info:
  title: Billing
  description: Billing
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: sample_store
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
paths:
  /application_charges.json:
    post:
      tags:
        - ApplicationCharge
      summary: Creates an application charge
      operationId: CreateApplicationCharge
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - ApplicationCharge
      summary: Retrieves a list of application charges
      operationId: RetrieveListOfApplicationCharges
      parameters:
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
        - name: since_id
          in: query
          description: Restrict results to after the specified ID.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationChargeList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/application_charges/{application_charge_id}.json':
    get:
      tags:
        - ApplicationCharge
      summary: Retrieves an application charge
      operationId: RetrieveApplicationCharge
      parameters:
        - name: application_charge_id
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /application_credits.json:
    post:
      tags:
        - ApplicationCredit
      summary: Creates an application credit
      operationId: CreateApplicationCredit
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCreditItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - ApplicationCredit
      summary: Retrieves all application credits
      operationId: RetrieveAllApplicationCredits
      parameters:
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCreditList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/application_credits/{application_credit_id}.json':
    get:
      tags:
        - ApplicationCredit
      summary: Retrieves a single application credit
      operationId: RetrieveSingleApplicationCredit
      parameters:
        - name: application_credit_id
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCreditItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /recurring_application_charges.json:
    post:
      tags:
        - RecurringApplicationCharge
      summary: Creates a recurring application charge
      operationId: CreateRecurringApplicationCharge
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecurringApplicationChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - RecurringApplicationCharge
      summary: Retrieves a list of recurring application charges
      operationId: RetrieveListOfRecurringApplicationCharges
      parameters:
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
        - name: since_id
          in: query
          description: Restrict results to after the specified ID.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecurringApplicationChargeList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/recurring_application_charges/{recurring_application_charge_id}.json':
    get:
      tags:
        - RecurringApplicationCharge
      summary: Retrieves a single charge
      operationId: RetrieveSingleCharge
      parameters:
        - name: recurring_application_charge_id
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecurringApplicationChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - RecurringApplicationCharge
      summary: Cancels a recurring application charge
      operationId: CancelRecurringApplicationCharge
      parameters:
        - name: recurring_application_charge_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/recurring_application_charges/{recurring_application_charge_id}/customize.json':
    put:
      tags:
        - RecurringApplicationCharge
      summary: Updates the capped amount of a recurring application charge
      operationId: UpdateTheCappedAmountOfRecurringApplicationCharge
      parameters:
        - name: recurring_application_charge_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecurringApplicationChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/recurring_application_charges/{recurring_application_charge_id}/usage_charges.json':
    post:
      tags:
        - UsageCharge
      summary: Creates a usage charge
      operationId: CreateUsageCharge
      parameters:
        - name: recurring_application_charge_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - UsageCharge
      summary: Retrieves a list of usage charges
      operationId: RetrieveListOfUsageCharges
      parameters:
        - name: recurring_application_charge_id
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageChargeList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/recurring_application_charges/{recurring_application_charge_id}/usage_charges/{usage_charge_id}.json':
    get:
      tags:
        - UsageCharge
      summary: Retrieves a single charge
      operationId: RetrieveSingleCharge
      parameters:
        - name: recurring_application_charge_id
          in: path
          required: true
          schema:
            type: string
        - name: usage_charge_id
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageChargeItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ApplicationCharge:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 255
          type: string
          nullable: true
        api_client_id:
          type: integer
          format: int32
        price:
          maximum: 10000
          minimum: 0.5
          type: number
          format: double
          nullable: true
        status:
          $ref: '#/components/schemas/ApplicationChargeStatus'
        return_url:
          type: string
          nullable: true
        test:
          type: boolean
          nullable: true
        created_at:
          type: string
          format: date-time
          nullable: true
        updated_at:
          type: string
          format: date-time
          nullable: true
        charge_type:
          type: string
          nullable: true
        decorated_return_url:
          type: string
          nullable: true
      additionalProperties: { }
    ApplicationChargeItem:
      type: object
      properties:
        application_charge:
          $ref: '#/components/schemas/ApplicationCharge'
      additionalProperties: { }
    ApplicationChargeList:
      type: object
      properties:
        application_charges:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationCharge'
          nullable: true
      additionalProperties: { }
    ApplicationChargeStatus:
      enum:
        - pending
        - accepted
        - active
        - declined
        - expired
      type: string
      additionalProperties: { }
    ApplicationCredit:
      type: object
      properties:
        id:
          type: integer
          description: The object's unique id.
          format: int64
          nullable: true
        admin_graphql_api_id:
          type: string
          nullable: true
        description:
          type: string
          description: The description of the application credit.
          nullable: true
        amount:
          type: number
          description: The amount refunded by the application credit.
          format: double
          nullable: true
        test:
          type: boolean
          description: States whether or not the application credit is a test transaction. Valid values are true or null.
          nullable: true
      additionalProperties: { }
      description: 'An object representing Shopify''s ApplicationCredit object, which can be used to offer credits for payments made via the Application Charge, Recurring Application Charge, and Usage Charge APIs.'
    ApplicationCreditItem:
      type: object
      properties:
        application_credit:
          $ref: '#/components/schemas/ApplicationCredit'
      additionalProperties: { }
    ApplicationCreditList:
      type: object
      properties:
        application_credits:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationCredit'
          nullable: true
      additionalProperties: { }
    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
    RecurringApplicationCharge:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        api_client_id:
          type: integer
          format: int64
        price:
          type: number
          format: double
          nullable: true
        status:
          $ref: '#/components/schemas/RecurringApplicationChargeStatus'
        return_url:
          type: string
          nullable: true
        billing_on:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        test:
          type: boolean
          nullable: true
        activated_on:
          type: string
          format: date-time
          nullable: true
        cancelled_on:
          type: string
          format: date-time
          nullable: true
        trial_days:
          type: integer
          format: int32
          nullable: true
        trial_ends_on:
          type: string
          format: date-time
          nullable: true
        decorated_return_url:
          type: string
          nullable: true
      additionalProperties: { }
    RecurringApplicationChargeItem:
      type: object
      properties:
        recurring_application_charge:
          $ref: '#/components/schemas/RecurringApplicationCharge'
      additionalProperties: { }
    RecurringApplicationChargeList:
      type: object
      properties:
        recurring_application_charges:
          type: array
          items:
            $ref: '#/components/schemas/RecurringApplicationCharge'
          nullable: true
      additionalProperties: { }
    RecurringApplicationChargeStatus:
      enum:
        - pending
        - accepted
        - active
        - declined
        - expired
        - frozen
        - cancelled
      type: string
      additionalProperties: { }
    UsageCharge:
      type: object
      properties:
        id:
          type: integer
          description: The object's unique id.
          format: int64
          nullable: true
        admin_graphql_api_id:
          type: string
          nullable: true
        created_at:
          type: string
          description: The date and time when the usage charge was created.
          format: date-time
          nullable: true
        description:
          type: string
          description: The name of the usage charge.
          nullable: true
        price:
          type: number
          description: The price of the usage charge.
          format: double
          nullable: true
        recurring_application_charge_id:
          type: integer
          description: The recurring application charge the usage charge belongs to.
          format: int64
          nullable: true
        updated_at:
          type: string
          description: The date and time when the usage charge was last updated.
          format: date-time
          nullable: true
      additionalProperties: { }
      description: Represents a variable monthly fee for an app or a service.
    UsageChargeItem:
      type: object
      properties:
        usage_charge:
          $ref: '#/components/schemas/UsageCharge'
      additionalProperties: { }
    UsageChargeList:
      type: object
      properties:
        usage_charges:
          type: array
          items:
            $ref: '#/components/schemas/UsageCharge'
          nullable: true
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]