openapi: 3.0.1
info:
  title: Marketing Event
  description: Marketing Event
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /marketing_events.json:
    get:
      tags:
        - MarketingEvent
      summary: Retrieves a list of all marketing events
      operationId: ListMarketingEvents
      parameters:
        - name: limit
          in: query
          description: The amount of results to return.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          schema:
            type: string
        - name: offset
          in: query
          description: The number of marketing events to skip.
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketingEventList'
    post:
      tags:
        - MarketingEvent
      summary: Creates a marketing event
      operationId: CreateMarketingEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMarketingEventRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateMarketingEventRequest'
        required: true
      responses:
        '201':
          description: Created
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketingEventItem'
  /marketing_events/count.json:
    get:
      tags:
        - MarketingEvent
      summary: Retrieves a count of all marketing events
      operationId: CountMarketingEvents
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountItem'
  '/marketing_events/{marketing_event_id}.json':
    get:
      tags:
        - MarketingEvent
      summary: Retrieves a single marketing event
      operationId: GetMarketingEvent
      parameters:
        - name: marketing_event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketingEventItem'
    put:
      tags:
        - MarketingEvent
      summary: Updates a marketing event
      operationId: UpdateMarketingEvent
      parameters:
        - name: marketing_event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMarketingEventRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateMarketingEventRequest'
        required: true
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketingEventItem'
    delete:
      tags:
        - MarketingEvent
      summary: Deletes a marketing event
      operationId: DeleteMarketingEvent
      parameters:
        - name: marketing_event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  '/marketing_events/{marketing_event_id}/engagements.json':
    post:
      tags:
        - MarketingEvent
      summary: Creates marketing engagements on a marketing event
      operationId: CreateMarketingEngagementsOnMarketingEvent
      parameters:
        - name: marketing_event_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: occurred_on
          in: query
          description: 'The date that these engagements occurred on, in the format “YYYY-MM-DD”.'
          schema:
            type: string
        - name: ad_spend
          in: query
          description: 'The total ad spend for the day, if the marketing event is a paid ad with a daily spend.'
          schema:
            type: string
        - name: clicks_count
          in: query
          description: The total number of clicks on the marketing event for the day.
          schema:
            type: string
        - name: comments_count
          in: query
          description: The total number of comments for the day.
          schema:
            type: string
        - name: favorites_count
          in: query
          description: The total number of favorites for the day.
          schema:
            type: string
        - name: impressions_count
          in: query
          description: 'The total number of impressions for the day. An impression occurs when the marketing event is served to a customer, either as a email or through a marketing channel.'
          schema:
            type: string
        - name: is_cumulative
          in: query
          description: Whether the engagements are reported as lifetime values rather than daily totals.
          schema:
            type: string
        - name: shares_count
          in: query
          description: The total number of shares for the day.
          schema:
            type: string
        - name: views_count
          in: query
          description: 'The total number of views for the day. A view occurs when a customer reads the marketing event that was served to them, for example, if the customer opens the email or spends time looking at a Facebook post.'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMarketingEventRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateMarketingEventRequest'
        required: true
      responses:
        '201':
          description: Created
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngagementList'
components:
  schemas:
    CountItem:
      type: object
      properties:
        count:
          type: integer
          format: int32
      additionalProperties: { }
    CreateMarketingEvent:
      type: object
      additionalProperties: { }
    CreateMarketingEventRequest:
      required:
        - marketing_event
      type: object
      properties:
        marketing_event:
          $ref: '#/components/schemas/CreateMarketingEvent'
      additionalProperties: { }
    Engagement:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: { }
    EngagementList:
      required:
        - engagements
      type: object
      properties:
        engagements:
          type: array
          items:
            $ref: '#/components/schemas/Engagement'
      additionalProperties: { }
    MarketingEvent:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: { }
    MarketingEventItem:
      required:
        - marketing_event
      type: object
      properties:
        marketing_event:
          $ref: '#/components/schemas/MarketingEvent'
      additionalProperties: { }
    MarketingEventList:
      required:
        - marketing_events
      type: object
      properties:
        marketing_events:
          type: array
          items:
            $ref: '#/components/schemas/MarketingEvent'
      additionalProperties: { }
    UpdateMarketingEvent:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: { }
    UpdateMarketingEventRequest:
      required:
        - marketing_event
      type: object
      properties:
        marketing_event:
          $ref: '#/components/schemas/UpdateMarketingEvent'
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]