openapi: 3.0.1
info:
  title: Discounts
  description: Discounts
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: sample_store
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
paths:
  '/price_rules/{price_rule_id}/discount_codes.json':
    post:
      tags:
        - DiscountCode
      summary: Creates a discount code
      operationId: CreateDiscountCode
      parameters:
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - DiscountCode
      summary: Retrieves a list of discount codes
      operationId: RetrieveListOfDiscountCodes
      parameters:
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/price_rules/{price_rule_id}/discount_codes/{discount_code_id}.json':
    put:
      tags:
        - DiscountCode
      summary: Updates an existing discount code
      operationId: UpdateExistingDiscountCode
      parameters:
        - name: discount_code_id
          in: path
          required: true
          schema:
            type: string
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - DiscountCode
      summary: Retrieves a single discount code
      operationId: RetrieveSingleDiscountCode
      parameters:
        - name: discount_code_id
          in: path
          required: true
          schema:
            type: string
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - DiscountCode
      summary: Deletes a discount code
      operationId: DeleteDiscountCode
      parameters:
        - name: discount_code_id
          in: path
          required: true
          schema:
            type: string
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /discount_codes/lookup.json:
    get:
      tags:
        - DiscountCode
      summary: Retrieves the location of a discount code
      operationId: RetrieveTheLocationOfDiscountCode
      parameters:
        - name: code
          in: query
          description: Retrieves the location of a discount code by code name.
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /discount_codes/count.json:
    get:
      tags:
        - DiscountCode
      summary: Retrieves a count of discount codes for a shop
      operationId: RetrieveCountOfDiscountCodesForShop
      parameters:
        - name: times_used
          in: query
          description: Show discount codes with times used.
          schema:
            type: string
        - name: times_used_max
          in: query
          description: Show discount codes used greater than or equal to this value.
          schema:
            type: string
        - name: times_used_min
          in: query
          description: Show discount codes used less than or equal to this value.
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/price_rules/{price_rule_id}/batch.json':
    post:
      tags:
        - DiscountCode
      summary: Creates a discount code creation job
      operationId: CreateDiscountCodeCreationJob
      parameters:
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/price_rules/{price_rule_id}/batch/{batch_id}.json':
    get:
      tags:
        - DiscountCode
      summary: Retrieves a discount code creation job
      operationId: RetrieveDiscountCodeCreationJob
      parameters:
        - name: batch_id
          in: path
          required: true
          schema:
            type: string
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/price_rules/{price_rule_id}/batch/{batch_id}/discount_codes.json':
    get:
      tags:
        - DiscountCode
      summary: Retrieves a list of discount codes for a discount code creation job
      operationId: RetrieveListOfDiscountCodesForDiscountCodeCreationJob
      parameters:
        - name: batch_id
          in: path
          required: true
          schema:
            type: string
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /price_rules.json:
    post:
      tags:
        - PriceRule
      summary: Creates a price rule
      operationId: CreatePriceRule
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - PriceRule
      summary: Retrieves a list of price rules
      operationId: RetrieveListOfPriceRules
      parameters:
        - name: created_at_max
          in: query
          description: Show price rules created before date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: created_at_min
          in: query
          description: Show price rules created after date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: ends_at_max
          in: query
          description: Show price rules ending before date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: ends_at_min
          in: query
          description: Show price rules ending after date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of results to retrieve.
          schema:
            type: string
        - name: since_id
          in: query
          description: Restrict results to after the specified ID.
          schema:
            type: string
        - name: starts_at_max
          in: query
          description: Show price rules starting before date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: starts_at_min
          in: query
          description: Show price rules starting after date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: times_used
          in: query
          description: Show price rules with times used.
          schema:
            type: string
        - name: updated_at_max
          in: query
          description: Show price rules last updated before date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
        - name: updated_at_min
          in: query
          description: Show price rules last updated after date (format 2017-03-25T16:15:47-04:00).
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/price_rules/{price_rule_id}.json':
    put:
      tags:
        - PriceRule
      summary: Updates an existing a price rule
      operationId: UpdateExistingPriceRule
      parameters:
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - PriceRule
      summary: Retrieves a single price rule
      operationId: RetrieveSinglePriceRule
      parameters:
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - PriceRule
      summary: Remove an existing PriceRule
      operationId: RemoveExistingPriceRule
      parameters:
        - name: price_rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /price_rules/count.json:
    get:
      tags:
        - PriceRule
      summary: Retrieves a count of all price rules
      operationId: RetrieveCountOfAllPriceRules
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]