openapi: 3.0.1
info:
  title: Analytics
  description: Reporting and Analytics
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /reports.json:
    get:
      tags:
        - Report
      summary: Retrieves a list of reports
      operationId: ListReports
      parameters:
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
        - name: ids
          in: query
          description: A comma-separated list of report IDs.
          style: form
          explode: false
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: limit
          in: query
          description: The amount of results to return.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
        - name: since_id
          in: query
          description: Restrict results to after the specified ID.
          schema:
            type: integer
            format: int64
        - name: updated_at_max
          in: query
          description: 'Show reports last updated before date. (format: 2014-04-25T16:15:47-04:00)'
          schema:
            type: string
            format: date-time
        - name: updated_at_min
          in: query
          description: 'Show reports last updated after date. (format: 2014-04-25T16:15:47-04:00)'
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Success
          headers:
            Link:
              description: 'The link header includes a `rel` parameter, where `relation-types` describes the relation of the linked page to the current page of results. The value can either be `previous` or `next`. If your initial request doesn''t return enough records to generate an additional page of results, then the response won''t have a link header.'
              schema:
                type: string
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportList'
    post:
      tags:
        - Report
      summary: Creates a new report
      operationId: CreateReport
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReportRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateReportRequest'
        required: true
      responses:
        '201':
          description: Created
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportItem'
        '400':
          description: Bad Request
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportError'
  '/reports/{report_id}.json':
    get:
      tags:
        - Report
      summary: Retrieves a single report
      operationId: GetReport
      parameters:
        - name: report_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: fields
          in: query
          description: A comma-separated list of fields to include in the response.
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportItem'
    put:
      tags:
        - Report
      summary: Updates a report
      operationId: UpdateReport
      parameters:
        - name: report_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReportRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateReportRequest'
        required: true
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportItem'
        '422':
          description: Client Error
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportError'
    delete:
      tags:
        - Report
      summary: Deletes a report
      operationId: DeleteReport
      parameters:
        - name: report_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
components:
  schemas:
    CreateReport:
      type: object
      properties:
        category:
          type: string
          description: 'The category for the report. When you create a report, the API will return `custom_app_reports`.'
          nullable: true
        name:
          type: string
          description: 'The name of the report. Maximum length: 255 characters.'
          nullable: true
        shopify_ql:
          type: string
          description: 'The ShopifyQL query that generates the report.See [Shopify Query Language](/api/admin/rest/reference/analytics/shopify-ql).'
          nullable: true
      additionalProperties: false
    CreateReportRequest:
      required:
        - report
      type: object
      properties:
        report:
          $ref: '#/components/schemas/CreateReport'
      additionalProperties: false
    Report:
      required:
        - id
      type: object
      properties:
        category:
          type: string
          description: 'The category for the report. When you create a report, the API will return `custom_app_reports`.'
          nullable: true
        name:
          type: string
          description: 'The name of the report. Maximum length: 255 characters.'
          nullable: true
        shopify_ql:
          type: string
          description: 'The ShopifyQL query that generates the report.See [Shopify Query Language](/api/admin/rest/reference/analytics/shopify-ql).'
          nullable: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
        created_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the asset was created.'
          format: date-time
          nullable: true
        updated_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when an asset was last updated.'
          format: date-time
          nullable: true
      additionalProperties: { }
    ReportError:
      required:
        - errors
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ReportErrorDetails'
      additionalProperties: { }
    ReportErrorDetails:
      type: object
      properties:
        base:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: { }
    ReportItem:
      required:
        - report
      type: object
      properties:
        report:
          $ref: '#/components/schemas/Report'
      additionalProperties: { }
    ReportList:
      required:
        - reports
      type: object
      properties:
        reports:
          type: array
          items:
            $ref: '#/components/schemas/Report'
      additionalProperties: { }
    UpdateReport:
      required:
        - id
      type: object
      properties:
        category:
          type: string
          description: 'The category for the report. When you create a report, the API will return `custom_app_reports`.'
          nullable: true
        name:
          type: string
          description: 'The name of the report. Maximum length: 255 characters.'
          nullable: true
        shopify_ql:
          type: string
          description: 'The ShopifyQL query that generates the report.See [Shopify Query Language](/api/admin/rest/reference/analytics/shopify-ql).'
          nullable: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: false
    UpdateReportRequest:
      required:
        - report
      type: object
      properties:
        report:
          $ref: '#/components/schemas/UpdateReport'
      additionalProperties: false
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]