openapi: 3.0.1
info:
  title: Tender Transaction
  description: Tender Transaction
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /tender_transactions.json:
    get:
      tags:
        - TenderTransaction
      summary: Retrieves a list of tender transactions
      operationId: ListTenderTransactions
      parameters:
        - name: limit
          in: query
          description: The maximum number of results to retrieve.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
        - name: order
          in: query
          description: Show tender transactions ordered by processed_at in ascending or descending order.
          schema:
            type: string
        - name: processed_at
          in: query
          description: Show tender transactions processed at the specified date.
          schema:
            type: string
            format: date-time
        - name: processed_at_max
          in: query
          description: Show tender transactions processed_at or before the specified date.
          schema:
            type: string
            format: date-time
        - name: processed_at_min
          in: query
          description: Show tender transactions processed_at or after the specified date.
          schema:
            type: string
            format: date-time
        - name: since_id
          in: query
          description: Retrieve only transactions after the specified ID.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenderTransactionList'
components:
  schemas:
    TenderTransaction:
      required:
        - id
      type: object
      properties:
        order_id:
          type: integer
          description: The ID of the order that the tender transaction belongs to.
          format: int64
          nullable: true
        amount:
          type: number
          description: The amount of the tender transaction in the shop's currency.
          format: decimal
          nullable: true
        currency:
          type: string
          description: 'The three-letter code ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format) for the currency used for the tender transaction.'
          nullable: true
        user_id:
          type: integer
          description: 'The ID of the user logged into the Shopify POS device that processed the tender transaction, if applicable.'
          format: int64
          nullable: true
        test:
          type: boolean
          description: Whether the tender transaction is a test transaction.
          nullable: true
        processed_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the tender transaction was processed.'
          format: date-time
          nullable: true
        remote_reference:
          type: string
          description: The remote (gateway) reference associated with the tender.
          nullable: true
        payment_details:
          type: string
          description: "Information about the payment instrument used for this transaction. It has the following properties: \r\n\r\n*   **credit_card_company**: The name of the company that issued the customer's credit card. \r\n*   **credit_card_number**: The customer's credit card number, with most of the leading digits redacted."
          nullable: true
        payment_method:
          type: string
          description: "Information about the payment method used for this transaction. Valid values: \r\n\r\n*   **credit_card** \r\n*   **cash** \r\n*   **android_pay** \r\n*   **apple_pay** \r\n*   **google_pay** \r\n*   **samsung_pay** \r\n*   **shopify_pay** \r\n*   **amazon** \r\n*   **klarna** \r\n*   **paypal** \r\n*   **unknown** \r\n*   **other**"
          nullable: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: { }
    TenderTransactionList:
      required:
        - tender_transactions
      type: object
      properties:
        tender_transactions:
          type: array
          items:
            $ref: '#/components/schemas/TenderTransaction'
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]