openapi: 3.0.1
info:
  title: Deprecated API Calls
  description: Deprecated API Calls
  version: '2023-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2023-04'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /deprecated_api_calls.json:
    get:
      tags:
        - DeprecatedApiCalls
      operationId: ListDeprecatedAPICalls
      responses:
        '200':
          description: Success
          headers:
            Link:
              description: 'The link header includes a `rel` parameter, where `relation-types` describes the relation of the linked page to the current page of results. The value can either be `previous` or `next`. If your initial request doesn''t return enough records to generate an additional page of results, then the response won''t have a link header.'
              schema:
                type: string
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeprecatedApiCallList'
components:
  schemas:
    ApiType:
      enum:
        - REST
        - Webhook
        - GraphQL
      type: string
      additionalProperties: { }
    DeprecatedApiCall:
      type: object
      properties:
        data_updated_at:
          type: string
          description: 'The date and time ([ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601)) when the data was last updated.'
          nullable: true
        deprecated_api_calls:
          type: string
          description: "A list of deprecated API calls made by the authenticated app in the past 30 days. Each object has the following properties:\r\n\r\n*   `api_type`: The type of API that the call was made to. Valid values: `REST`, `Webhook`, `GraphQL`. \r\n*   `description`: A description of the deprecation and any required migration steps. \r\n*   `documentation_url`: The documentation URL to the deprecated change. \r\n*   `endpoint`: A description of the REST endpoint, webhook topic, or GraphQL field called. \r\n*   `last_call_at`: The timestamp ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format) when the last deprecated API call was made. \r\n*   `migration_deadline`: The time ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format) when the deprecated API call will be removed. \r\n*   `graphql_schema_name`: The name of the GraphQL schema. If the call wasn't made to a GraphQL API, then this value is `null`. \r\n*   `version`: The earliest API version to migrate to in order to avoid making the deprecated API calls."
          nullable: true
        api_type:
          $ref: '#/components/schemas/ApiType'
        description:
          type: string
          description: A description of the deprecation and any required migration steps.
          nullable: true
        documentation_url:
          type: string
          description: The documentation URL to the deprecated change.
          nullable: true
        endpoint:
          type: string
          description: 'description of the REST endpoint, webhook topic, or GraphQL field called.'
          nullable: true
        last_call_at:
          type: string
          description: The timestamp (ISO 4217 format) when the last deprecated API call was made.
          format: date-time
        migration_deadline:
          type: string
          description: The time (ISO 4217 format) when the deprecated API call will be removed.
          format: date-time
        graphql_schema_name:
          type: string
          description: 'The name of the GraphQL schema. If the call wasn''t made to a GraphQL API, then this value is null.'
          nullable: true
        version:
          type: string
          description: The earliest API version to migrate to in order to avoid making the deprecated API calls.
          nullable: true
        created_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the asset was created.'
          format: date-time
          nullable: true
        updated_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when an asset was last updated.'
          format: date-time
          nullable: true
      additionalProperties: { }
    DeprecatedApiCallList:
      required:
        - deprecated_api_calls
      type: object
      properties:
        deprecated_api_calls:
          type: array
          items:
            $ref: '#/components/schemas/DeprecatedApiCall'
      additionalProperties: { }
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]