openapi: 3.0.1
info:
  title: Plus
  description: Plus
  version: '2022-04'
servers:
  - url: 'https://{store_name}.myshopify.com/admin/api/{api_version}'
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
      api_version:
        default: '2022-04'
        description: The api version.
  - url: 'https://{store_name}.myshopify.com/admin'
    description: Some endpoints do not use the standard routing. This is an alternate.
    variables:
      store_name:
        default: '{{store_name}}'
        description: The sub-domain of the storefront.
paths:
  /gift_cards.json:
    get:
      tags:
        - GiftCard
      summary: Retrieves a list of gift cards
      operationId: ListGiftCards
      parameters:
        - name: fields
          in: query
          description: 'Show only certain fields, specified by a comma-separated list of field names.'
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of results to show.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
        - name: since_id
          in: query
          description: Restrict results to after the specified ID.
          schema:
            type: integer
            format: int64
        - name: status
          in: query
          description: 'Retrieve gift cards with a given status. Valid values:'
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
    post:
      tags:
        - GiftCard
      summary: Creates a gift card
      operationId: CreateGiftCard
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGiftCardRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateGiftCardRequest'
        required: true
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  '/gift_cards/{gift_card_id}.json':
    get:
      tags:
        - GiftCard
      summary: Retrieves a single gift card
      operationId: GetGiftCard
      parameters:
        - name: gift_card_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
    put:
      tags:
        - GiftCard
      summary: Updates an existing gift card
      operationId: UpdateGiftCard
      parameters:
        - name: gift_card_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGiftCardRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateGiftCardRequest'
        required: true
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  /gift_cards/count.json:
    get:
      tags:
        - GiftCard
      summary: Retrieves a count of gift cards
      operationId: CountGiftCards
      parameters:
        - name: status
          in: query
          description: 'Count gift cards with a given status. Valid values:'
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountItem'
  '/gift_cards/{gift_card_id}/disable.json':
    post:
      tags:
        - GiftCard
      summary: Disables a gift card
      operationId: DisableGiftCard
      parameters:
        - name: gift_card_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  /gift_cards/search.json:
    get:
      tags:
        - GiftCard
      summary: Searches for gift cards
      operationId: SearchForGiftCards
      parameters:
        - name: fields
          in: query
          description: 'Show only certain fields, specified by a comma-separated list of field names.'
          schema:
            type: string
        - name: limit
          in: query
          description: The maximum number of results to retrieve.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
        - name: order
          in: query
          description: The field and direction to order results by.
          schema:
            type: string
        - name: query
          in: query
          description: The text to search for.
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  /users.json:
    get:
      tags:
        - User
      summary: Retrieves a list of all users
      operationId: ListUsers
      parameters:
        - name: limit
          in: query
          description: The maximum number of results to show on a page.
          schema:
            type: integer
            format: int32
        - name: page_info
          in: query
          description: A unique ID used to access a certain page of results.
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  '/users/{user_id}.json':
    get:
      tags:
        - User
      summary: Retrieves a single user
      operationId: GetUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
  /users/current.json:
    get:
      tags:
        - User
      summary: Retrieves the currently logged-in user
      operationId: GetCurrentlyLoggedInUser
      responses:
        '200':
          description: Success
          headers:
            X-Shopify-Shop-Api-Call-Limit:
              description: How many requests you’ve made for a particular store
              schema:
                type: string
            Retry-After:
              description: Contains the number of seconds to wait until you can make a request again.
              schema:
                type: string
components:
  schemas:
    CountItem:
      type: object
      properties:
        count:
          type: integer
          format: int32
      additionalProperties: { }
    CreateGiftCard:
      type: object
      properties:
        api_client_id:
          type: integer
          description: The ID of the client that issued the gift card.
          format: int64
          nullable: true
        balance:
          type: number
          description: The balance of the gift card.
          format: decimal
          nullable: true
        code:
          type: string
          description: 'The gift card code, which is a string of alphanumeric characters. For security reasons, this is available only upon creation of the gift card. (minimum: 8 characters, maximum: 20 characters)'
          nullable: true
        created_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the gift card was created.'
          format: date-time
          nullable: true
        currency:
          type: string
          description: The currency of the gift card.
          nullable: true
        customer_id:
          type: integer
          description: The ID of the customer associated with this gift card.
          format: int64
          nullable: true
        disabled_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the gift card was disabled.'
          format: date-time
          nullable: true
        expires_on:
          type: string
          description: The date (`YYYY-MM-DD` format) when the gift card expires. Returns `null` if the gift card doesn't have an expiration date.
          format: date-time
          nullable: true
        initial_value:
          type: number
          description: The initial value of the gift card when it was created.
          format: decimal
          nullable: true
        last_characters:
          type: string
          description: 'The last four characters of the gift card code. Because gift cards are alternative payment methods, the full code cannot be retrieved.'
          nullable: true
        line_item_id:
          type: integer
          description: 'The ID of the line item that initiated the creation of this gift card, if it was created by an order.'
          format: int64
          nullable: true
        note:
          type: string
          description: An optional note that a merchant can attach to the gift card that isn't visible to customers.
          nullable: true
        order_id:
          type: integer
          description: 'The ID of the order that initiated the creation of this gift card, if it was created by an order.'
          format: int64
          nullable: true
        template_suffix:
          type: string
          description: 'The suffix of the Liquid template that''s used to render the gift card online. For example, if the value is `birthday`, then the gift card is rendered using the template `gift_card.birthday.liquid`. When the value is `null`, the default `gift_card.liquid` template is used.'
          nullable: true
        user_id:
          type: integer
          description: 'The ID of the user that issued the gift card, if it was issued by a user.'
          format: int64
          nullable: true
        updated_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the gift card was last modified.'
          format: date-time
          nullable: true
      additionalProperties: { }
    CreateGiftCardRequest:
      required:
        - gift_card
      type: object
      properties:
        gift_card:
          $ref: '#/components/schemas/CreateGiftCard'
      additionalProperties: false
    UpdateGiftCard:
      required:
        - id
      type: object
      properties:
        api_client_id:
          type: integer
          description: The ID of the client that issued the gift card.
          format: int64
          nullable: true
        balance:
          type: number
          description: The balance of the gift card.
          format: decimal
          nullable: true
        code:
          type: string
          description: 'The gift card code, which is a string of alphanumeric characters. For security reasons, this is available only upon creation of the gift card. (minimum: 8 characters, maximum: 20 characters)'
          nullable: true
        created_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the gift card was created.'
          format: date-time
          nullable: true
        currency:
          type: string
          description: The currency of the gift card.
          nullable: true
        customer_id:
          type: integer
          description: The ID of the customer associated with this gift card.
          format: int64
          nullable: true
        disabled_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the gift card was disabled.'
          format: date-time
          nullable: true
        expires_on:
          type: string
          description: The date (`YYYY-MM-DD` format) when the gift card expires. Returns `null` if the gift card doesn't have an expiration date.
          format: date-time
          nullable: true
        initial_value:
          type: number
          description: The initial value of the gift card when it was created.
          format: decimal
          nullable: true
        last_characters:
          type: string
          description: 'The last four characters of the gift card code. Because gift cards are alternative payment methods, the full code cannot be retrieved.'
          nullable: true
        line_item_id:
          type: integer
          description: 'The ID of the line item that initiated the creation of this gift card, if it was created by an order.'
          format: int64
          nullable: true
        note:
          type: string
          description: An optional note that a merchant can attach to the gift card that isn't visible to customers.
          nullable: true
        order_id:
          type: integer
          description: 'The ID of the order that initiated the creation of this gift card, if it was created by an order.'
          format: int64
          nullable: true
        template_suffix:
          type: string
          description: 'The suffix of the Liquid template that''s used to render the gift card online. For example, if the value is `birthday`, then the gift card is rendered using the template `gift_card.birthday.liquid`. When the value is `null`, the default `gift_card.liquid` template is used.'
          nullable: true
        user_id:
          type: integer
          description: 'The ID of the user that issued the gift card, if it was issued by a user.'
          format: int64
          nullable: true
        updated_at:
          type: string
          description: 'The date and time ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format) when the gift card was last modified.'
          format: date-time
          nullable: true
        id:
          type: integer
          format: int64
        admin_graphql_api_id:
          type: string
          nullable: true
      additionalProperties: { }
    UpdateGiftCardRequest:
      required:
        - gift_card
      type: object
      properties:
        gift_card:
          $ref: '#/components/schemas/UpdateGiftCard'
      additionalProperties: false
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-Shopify-Access-Token
      in: header
security:
  - ApiKey: [ ]