//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace OpenShopify.Admin.Builder.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IThemeController
    {

        /// <summary>
        /// Retrieves a list of themes
        /// </summary>

        /// <param name="fields">Show only certain fields, specified by a comma-separated list of field names.</param>

        /// <returns>Retrieves a list of themes</returns>

        System.Threading.Tasks.Task RetrieveListOfThemesAsync(string? fields);

        /// <summary>
        /// Creates a theme
        /// </summary>

        /// <returns>Creates a theme</returns>

        System.Threading.Tasks.Task CreateThemeAsync();

        /// <summary>
        /// Retrieves a single theme by its ID
        /// </summary>


        /// <param name="fields">Show only certain fields, specified by a comma-separated list of field names.</param>

        /// <returns>Retrieves a single theme by its ID</returns>

        System.Threading.Tasks.Task RetrieveSingleThemeByItsIDAsync(string theme_id, string? fields);

        /// <summary>
        /// Modify an existing Theme
        /// </summary>


        /// <returns>Modify an existing Theme</returns>

        System.Threading.Tasks.Task ModifyExistingThemeAsync(string theme_id);

        /// <summary>
        /// Remove an existing Theme
        /// </summary>


        /// <returns>Remove an existing Theme</returns>

        System.Threading.Tasks.Task RemoveExistingThemeAsync(string theme_id);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]

    public partial class ThemeController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IThemeController _implementation;

        public ThemeController(IThemeController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Retrieves a list of themes
        /// </summary>
        /// <param name="fields">Show only certain fields, specified by a comma-separated list of field names.</param>
        /// <returns>Retrieves a list of themes</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("themes.json")]
        public System.Threading.Tasks.Task RetrieveListOfThemes([Microsoft.AspNetCore.Mvc.FromQuery] string? fields)
        {

            return _implementation.RetrieveListOfThemesAsync(fields);
        }

        /// <summary>
        /// Creates a theme
        /// </summary>
        /// <returns>Creates a theme</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("themes.json")]
        public System.Threading.Tasks.Task CreateTheme()
        {

            return _implementation.CreateThemeAsync();
        }

        /// <summary>
        /// Retrieves a single theme by its ID
        /// </summary>
        /// <param name="fields">Show only certain fields, specified by a comma-separated list of field names.</param>
        /// <returns>Retrieves a single theme by its ID</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("themes/{theme_id}.json")]
        public System.Threading.Tasks.Task RetrieveSingleThemeByItsID(string theme_id, [Microsoft.AspNetCore.Mvc.FromQuery] string? fields)
        {

            return _implementation.RetrieveSingleThemeByItsIDAsync(theme_id, fields);
        }

        /// <summary>
        /// Modify an existing Theme
        /// </summary>
        /// <returns>Modify an existing Theme</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("themes/{theme_id}.json")]
        public System.Threading.Tasks.Task ModifyExistingTheme(string theme_id)
        {

            return _implementation.ModifyExistingThemeAsync(theme_id);
        }

        /// <summary>
        /// Remove an existing Theme
        /// </summary>
        /// <returns>Remove an existing Theme</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("themes/{theme_id}.json")]
        public System.Threading.Tasks.Task RemoveExistingTheme(string theme_id)
        {

            return _implementation.RemoveExistingThemeAsync(theme_id);
        }

    }

    


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603