//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace OpenShopify.Admin.Builder.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class WebhookControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>
        /// Retrieves a list of webhooks
        /// </summary>
        /// <param name="address">Retrieve webhook subscriptions that send the POST request to this URI.</param>
        /// <param name="created_at_max">Retrieve webhook subscriptions that were created before a given date and time (format: 2014-04-25T16:15:47-04:00).</param>
        /// <param name="created_at_min">Retrieve webhook subscriptions that were created after a given date and time (format: 2014-04-25T16:15:47-04:00).</param>
        /// <param name="fields">Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.</param>
        /// <param name="limit">Maximum number of webhook subscriptions that should be returned. Setting this parameter outside the maximum range will return an error.</param>
        /// <param name="since_id">Restrict the returned list to webhook subscriptions whose id is greater than the specified since_id.</param>
        /// <param name="topic">Show webhook subscriptions with a given topic.
        /// <br/>
        /// <br/>For a list of valid values, refer to the &lt;a href="#topic-property-{{ current_version }}"&gt;&lt;code&gt;topic&lt;/code&gt; property&lt;/a&gt;.&gt;</param>
        /// <param name="updated_at_max">Retrieve webhooks that were updated after a given date and time (format: 2014-04-25T16:15:47-04:00).</param>
        /// <param name="updated_at_min">Retrieve webhooks that were updated before a given date and time (format: 2014-04-25T16:15:47-04:00).</param>
        /// <returns>Retrieves a list of webhooks</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("webhooks.json")]
        public abstract System.Threading.Tasks.Task RetrieveListOfWebhooks([Microsoft.AspNetCore.Mvc.FromQuery] string? address, [Microsoft.AspNetCore.Mvc.FromQuery] DateTime? created_at_max, [Microsoft.AspNetCore.Mvc.FromQuery] DateTime? created_at_min, [Microsoft.AspNetCore.Mvc.FromQuery] string? fields, [Microsoft.AspNetCore.Mvc.FromQuery] int? limit, string? page_info, [Microsoft.AspNetCore.Mvc.FromQuery] int? since_id, [Microsoft.AspNetCore.Mvc.FromQuery] string? topic, [Microsoft.AspNetCore.Mvc.FromQuery] DateTime? updated_at_max, [Microsoft.AspNetCore.Mvc.FromQuery] DateTime? updated_at_min);

        /// <summary>
        /// Create a new Webhook
        /// </summary>
        /// <returns>Create a new Webhook</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("webhooks.json")]
        public abstract System.Threading.Tasks.Task CreateNewWebhook([System.ComponentModel.DataAnnotations.Required] OpenShopify.Admin.Builder.Models.WebhookItem request);

        /// <summary>
        /// Receive a count of all Webhooks
        /// </summary>
        /// <param name="address">Webhook subscriptions that send the POST request to this URI.</param>
        /// <param name="topic">The topic of the webhook subscriptions.
        /// <br/>For a list of valid values, refer to the &lt;a href="#topic-property-{{ current_version }}"&gt;&lt;code&gt;topic&lt;/code&gt; property&lt;/a&gt;.</param>
        /// <returns>Receive a count of all Webhooks</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("webhooks/count.json")]
        public abstract System.Threading.Tasks.Task ReceiveCountOfAllWebhooks([Microsoft.AspNetCore.Mvc.FromQuery] string? address, [Microsoft.AspNetCore.Mvc.FromQuery] string? topic);

        /// <summary>
        /// Receive a single Webhook
        /// </summary>
        /// <param name="fields">Comma-separated list of the properties you want returned for each item in the result list. Use this parameter to restrict the returned list of items to only those properties you specify.</param>
        /// <returns>Receive a single Webhook</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("webhooks/{webhook_id}.json")]
        public abstract System.Threading.Tasks.Task ReceiveSingleWebhook(long webhook_id, [Microsoft.AspNetCore.Mvc.FromQuery] string? fields);

        /// <summary>
        /// Modify an existing Webhook
        /// </summary>
        /// <returns>Modify an existing Webhook</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("webhooks/{webhook_id}.json")]
        public abstract System.Threading.Tasks.Task ModifyExistingWebhook([System.ComponentModel.DataAnnotations.Required] OpenShopify.Admin.Builder.Models.WebhookItem request, long webhook_id);

        /// <summary>
        /// Remove an existing Webhook
        /// </summary>
        /// <returns>Remove an existing Webhook</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("webhooks/{webhook_id}.json")]
        public abstract System.Threading.Tasks.Task RemoveExistingWebhook(long webhook_id);

    }

    


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603