namespace OpenShopify.Admin.Builder.Models;

public record CreateMetafieldForBlogRequest : CreateMetafieldRequest;
public record CreateMetafieldForOrderRequest : CreateMetafieldRequest;
public record CreateMetafieldForProductImageRequest : CreateMetafieldRequest;
public record CreateMetafieldForProductRequest : CreateMetafieldRequest;
public record CreateMetafieldForCustomerRequest : CreateMetafieldRequest;
public record CreateMetafieldForDraftOrderRequest : CreateMetafieldRequest;
public record CreateMetafieldForPageRequest : CreateMetafieldRequest;
public record CreateMetafieldForArticleRequest : CreateMetafieldRequest;
public record CreateMetafieldForCollectionRequest : CreateMetafieldRequest;
public record CreateMetafieldForProductVariantRequest : CreateMetafieldRequest;



public record UpdateMetafieldForProductImageRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForCollectionRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForDraftOrderRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForCustomerRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForBlogRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForProductRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForArticleRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForPageRequest : UpdateMetafieldRequest;
public record UpdateMetafieldForOrderRequest : UpdateMetafieldRequest;