name: "Deploy to Github Packages"

on:
  push:
    tags:
      - 'v[0-9]+.*'

env:
  PROJECT_PATH: "src/Ocelli.OpenShopify/Ocelli.OpenShopify.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://nuget.pkg.github.com/OcelliSolutions/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Restore packages"
        run: dotnet restore

      - name: "Build projects"
        run: dotnet build --no-restore --configuration Release

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Authenticate"
        run: dotnet nuget add source --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_API_TOKEN }} --store-password-in-clear-text --name github ${{ env.NUGET_SOURCE_URL }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_TOKEN }} --source "github"
