//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace OpenShopify.Admin.Builder.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class AssignedFulfillmentOrderControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>
        /// Retrieves a list of fulfillment orders on a shop for a specific app
        /// </summary>
        /// <param name="assignment_status">The assigment status of the fulfillment orders that should be returned:</param>
        /// <param name="location_ids">The IDs of the assigned locations of the fulfillment orders that should be returned.</param>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("assigned_fulfillment_orders.json")]
        public abstract System.Threading.Tasks.Task ListFulfillmentOrdersOnShopForSpecificApp([Microsoft.AspNetCore.Mvc.FromQuery] string? assignment_status = null, [Microsoft.AspNetCore.Mvc.FromQuery] string? location_ids = null);

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AssignedFulfillmentOrderRequestStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"unsubmitted")]
        Unsubmitted = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"submitted")]
        Submitted = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"accepted")]
        Accepted = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"rejected")]
        Rejected = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"cancellation_requested")]
        CancellationRequested = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"cancellation_accepted")]
        CancellationAccepted = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"cancellation_rejected")]
        CancellationRejected = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"closed")]
        Closed = 7,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AssignedFulfillmentOrderStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"open")]
        Open = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"in_progress")]
        InProgress = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"cancelled")]
        Cancelled = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"incomplete")]
        Incomplete = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"closed")]
        Closed = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial record AssignedFulfillmentOrderOrig
    {
        /// <summary>
        /// The ID of the fulfillment order's assigned location. This is the location from which the order is expected to be fulfilled.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("assigned_location_id")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public long? AssignedLocationId { get; set; } = default!;

        /// <summary>
        /// The destination where the items should be sent upon fulfillment.
        /// 
        /// *   **id**: The ID of the fulfillment order destination. 
        /// *   **address1**: The first line of the address of the destination. 
        /// *   **address2**: The second line of the address of the destination. 
        /// *   **city**: The city of the destination. 
        /// *   **company**: The company of the destination. 
        /// *   **country**: The country of the destination. 
        /// *   **email**: The email of the customer at the destination. 
        /// *   **first_name**: The first name of the customer at the destination. 
        /// *   **last_name**: The last name of the customer at the destination. 
        /// *   **phone**: The phone number of the customer at the destination. 
        /// *   **province**: The province of the destination. 
        /// *   **zip**: The ZIP code of the destination.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("destination")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string? Destination { get; set; } = default!;

        /// <summary>
        /// Represents line items belonging to a fulfillment order:
        /// 
        /// *   **id**: The ID of the fulfillment order line item. 
        /// *   **shop_id**: The ID of the shop associated with the fulfillment order line item. 
        /// *   **fulfillment_order_id**: The ID of the fulfillment order associated with this line item. 
        /// *   **line_item_id**: The ID of the line item associated with this fulfillment order line item. 
        /// *   **inventory_item_id**: The ID of the inventory item associated with this fulfillment order line item. 
        /// *   **quantity**: The total number of units to be fulfilled. 
        /// *   **fulfillable_quantity**: The number of units remaining to be fulfilled.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("line_items")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string? LineItems { get; set; } = default!;

        /// <summary>
        /// The ID of the order that's associated with the fulfillment order.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("order_id")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public long? OrderId { get; set; } = default!;

        /// <summary>
        /// The request status of the fulfillment order. Valid values:
        /// 
        /// *   **unsubmitted**: The initial request status for the newly-created fulfillment orders. This is the only valid request status for fulfillment orders that aren't assigned to a fulfillment service.  
        /// *   **submitted**: The merchant requested fulfillment for this fulfillment order.  
        /// *   **accepted**: The fulfillment service accepted the merchant's fulfillment request.  
        /// *   **rejected**: The fulfillment service rejected the merchant's fulfillment request.  
        /// *   **cancellation_requested**: The merchant requested a cancellation of the fulfillment request for this fulfillment order.  
        /// *   **cancellation_accepted**: The fulfillment service accepted the merchant's fulfillment cancellation request.  
        /// *   **cancellation_rejected**: The fulfillment service rejected the merchant's fulfillment cancellation request.  
        /// *   **closed**: The fulfillment service closed the fulfillment order without completing it.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("request_status")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string? RequestStatus { get; set; } = default!;

        /// <summary>
        /// The ID of the shop that's associated with the fulfillment order.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("shop_id")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public long? ShopId { get; set; } = default!;

        /// <summary>
        /// The status of the fulfillment order. Valid values:
        /// 
        /// *   **open**: Default state for newly created fulfillment orders.  
        /// *   **in_progress**: The fulfillment order is being processed.  
        /// *   **cancelled**: The fulfillment order has been cancelled by the merchant.  
        /// *   **incomplete**: The fulfillment order cannot be completed as requested.  
        /// *   **closed**: The fulfillment order has been completed and closed.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("status")]

        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]   
        public string? Status { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603