//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace OpenShopify.Admin.Builder
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class FulfillmentServiceControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>
        /// Receive a list of all FulfillmentServices
        /// </summary>
        /// <returns>Receive a list of all FulfillmentServices</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/fulfillment_services.json")]
        public abstract System.Threading.Tasks.Task ReceiveListOfAllFulfillmentservices([Microsoft.AspNetCore.Mvc.FromQuery] string? scope = null);

        /// <summary>
        /// Create a new FulfillmentService
        /// </summary>
        /// <returns>Create a new FulfillmentService</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/fulfillment_services.json")]
        public abstract System.Threading.Tasks.Task CreateNewFulfillmentservice();

        /// <summary>
        /// Receive a single FulfillmentService
        /// </summary>
        /// <returns>Receive a single FulfillmentService</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/fulfillment_services/{fulfillment_service_id}.json")]
        public abstract System.Threading.Tasks.Task ReceiveSingleFulfillmentservice(string fulfillment_service_id);

        /// <summary>
        /// Modify an existing FulfillmentService
        /// </summary>
        /// <returns>Modify an existing FulfillmentService</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/fulfillment_services/{fulfillment_service_id}.json")]
        public abstract System.Threading.Tasks.Task ModifyExistingFulfillmentservice(string fulfillment_service_id);

        /// <summary>
        /// Remove an existing FulfillmentService
        /// </summary>
        /// <returns>Remove an existing FulfillmentService</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("admin/api/{api_version}/fulfillment_services/{fulfillment_service_id}.json")]
        public abstract System.Threading.Tasks.Task RemoveExistingFulfillmentservice(string fulfillment_service_id);

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FulfillmentService
    {
        /// <summary>
        /// The GraphQL GID for this fulfillment service.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("admin_graphql_api_id")]
        public string? Admin_graphql_api_id { get; set; } = default!;

        /// <summary>
        /// The callback URL the fulfillment service has registered for requests.
        /// <br/> If the Fulfillment Service has opted in to use fulfillment orders, then the callback_url/fulfillment_order_notification endpoint is also used to send fulfillment and cancellation requests.The callback_url field is required if inventory_management, tracking_support, or fulfillment_orders_opt_in is set to true.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("callback_url")]
        public string? Callback_url { get; set; } = default!;

        /// <summary>
        /// Specifies the format of the API output. Valid values are json and xml.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("format")]
        public string? Format { get; set; } = default!;

        /// <summary>
        /// Whether the fulfillment service wants to register for APIs related to fulfillment orders. To manage fulfillments using fulfillment orders, see Manage fulfillments with Fulfillment and FulfillmentOrder resources.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fulfillment_orders_opt_in")]
        public string? Fulfillment_orders_opt_in { get; set; } = default!;

        /// <summary>
        /// Human-readable unique identifier for this fulfillment service.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("handle")]
        public string? Handle { get; set; } = default!;

        /// <summary>
        /// States if the fulfillment service tracks product inventory and provides updates to Shopify. Valid values are "true" and "false".
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("inventory_management")]
        public string? Inventory_management { get; set; } = default!;

        /// <summary>
        /// The unique identifier of the location associated with the fulfillment service
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("location_id")]
        public string? Location_id { get; set; } = default!;

        /// <summary>
        /// The name of the fulfillment service as seen by merchants.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        /// <summary>
        /// A unique identifier for the fulfillment service provider.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("provider_id")]
        public string? Provider_id { get; set; } = default!;

        /// <summary>
        /// States if the fulfillment service requires products to be physically shipped. Valid values are "true" and "false".
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("requires_shipping_method")]
        public string? Requires_shipping_method { get; set; } = default!;

        /// <summary>
        /// States if the fulfillment service provides tracking numbers for packages. Valid values are "true" and "false".
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("tracking_support")]
        public string? Tracking_support { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603